import pickle
from pathlib import Path

import h5py
import numpy as np
from scipy.optimize import linear_sum_assignment


REPO_ROOT = Path(__file__).resolve().parents[1]

RESULTS_PATH = REPO_ROOT / (
    "results_run_20260828_190432_nb_of_samplings_1000_"
    "aligned_to_target_True.pkl"
)
OUTPUT_PATH = REPO_ROOT / "selected_mean_reconstruction_cases.h5"

# result_position is the position in the new nine-element pickle.
# source_number is 1-based, as in the visualization.
CASES = [
    # result_position, mixture_index, source_number, expected_snr, quality
    (0, 0, 1, 10.80, 1),
    (1, 306, 1, 13.90, 2),
    (2, 51, 5, 22.47, 3),
    (3, 51, 4, 30.54, 1),
    (4, 51, 1, 40.43, 2),
    (5, 927, 2, 35.51, 3),
    (6, 65, 5, 75.94, 1),
    (7, 394, 4, 50.81, 2),
    (8, 468, 3, 88.19, 3),
]

# These fields are generated by GalacticBinariesDataset and are not physical
# parameters stored in the original HDF5 params group.
AUXILIARY_PARAMETER_NAMES = {
    "source_mask",
    "freq_bin_start",
    "freq_bin_stop",
    "freq_bin_peak",
    "freq_support_width",
}


def to_numpy(value):
    if hasattr(value, "detach"):
        value = value.detach().cpu().numpy()
    return np.asarray(value)


def align_mean_to_target(prediction_mean, prediction_std, target, k):
    """Put the reconstructed mean and std in the true source order."""
    cost = np.mean(
        (prediction_mean[:k, None] - target[None, :k]) ** 2,
        axis=(-1, -2),
    )
    predicted_slots, target_slots = linear_sum_assignment(cost)

    aligned_mean = prediction_mean.copy()
    aligned_std = prediction_std.copy()
    aligned_mean[target_slots] = prediction_mean[predicted_slots]
    aligned_std[target_slots] = prediction_std[predicted_slots]
    return aligned_mean, aligned_std


with RESULTS_PATH.open("rb") as file:
    results = pickle.load(file)

if len(results) != len(CASES):
    raise ValueError(
        f"Expected {len(CASES)} results in {RESULTS_PATH.name}, "
        f"found {len(results)}."
    )

physical_parameter_names = sorted(
    set(results[0]["params"])
    - AUXILIARY_PARAMETER_NAMES
    - {"snr"}
)

output = {
    "result_position": [],
    "mixture_index": [],
    "source_number": [],
    "source_reconstructed": [],
    "source_reconstructed_std": [],
    "source_real": [],
    "snr": [],
    "reconstruction_quality": [],
    "residual_reconstructed": [],
    "residual_reconstructed_std": [],
    "residual_real": [],
}
parameter_values = {name: [] for name in physical_parameter_names}
sampling_counts = []

for result_position, mixture_index, source_number, expected_snr, quality in CASES:
    result = results[result_position]
    source_slot = source_number - 1
    k = int(result["K"])

    if int(result["mixture_index"]) != mixture_index:
        raise RuntimeError(
            f"Result {result_position}: expected mixture {mixture_index}, "
            f"found {result['mixture_index']}."
        )
    if source_slot >= k:
        raise IndexError(
            f"Mixture {mixture_index} has K={k}, so source "
            f"{source_number} does not exist."
        )

    target = to_numpy(result["target"])
    prediction_mean = to_numpy(result["prediction_mean"])
    prediction_std = to_numpy(result["prediction_std"])
    prediction_mean, prediction_std = align_mean_to_target(
        prediction_mean, prediction_std, target, k
    )

    params = result["params"]
    true_snr = float(to_numpy(params["snr"])[source_slot])
    if not np.isclose(true_snr, expected_snr, atol=0.01):
        raise RuntimeError(
            f"Result {result_position}, source {source_number}: SNR is "
            f"{true_snr:.4f}, expected {expected_snr:.2f}."
        )

    sampling_count = int(to_numpy(result["aligned_predictions"]).shape[0])
    sampling_counts.append(sampling_count)

    output["result_position"].append(result_position)
    output["mixture_index"].append(mixture_index)
    output["source_number"].append(source_number)
    output["source_reconstructed"].append(prediction_mean[source_slot])
    output["source_reconstructed_std"].append(prediction_std[source_slot])
    output["source_real"].append(target[source_slot])
    output["snr"].append(true_snr)
    output["reconstruction_quality"].append(quality)
    output["residual_reconstructed"].append(prediction_mean[-1])
    output["residual_reconstructed_std"].append(prediction_std[-1])
    output["residual_real"].append(target[-1])

    for parameter_name in physical_parameter_names:
        parameter_values[parameter_name].append(
            to_numpy(params[parameter_name])[source_slot]
        )

if len(set(sampling_counts)) != 1:
    raise RuntimeError(f"Inconsistent sampling counts: {sampling_counts}")

with h5py.File(OUTPUT_PATH, "w") as h5_file:
    h5_file.attrs["description"] = (
        "Nine manually selected source reconstructions averaged over "
        f"{sampling_counts[0]} stochastic samplings."
    )
    h5_file.attrs["number_of_samplings"] = sampling_counts[0]
    h5_file.attrs["source_reconstruction"] = "mean over aligned samplings"
    h5_file.attrs["element_indexing"] = "0-based"
    h5_file.attrs["source_numbering"] = "1-based"
    h5_file.attrs["reconstruction_quality"] = (
        "1=bad, 2=medium, 3=very good"
    )
    h5_file.attrs["results_file"] = RESULTS_PATH.name
    h5_file.attrs["input_aligned_to_target"] = bool(
        results[0].get("align_to_target", False)
    )
    h5_file.attrs["export_aligned_to_target"] = True

    h5_file.create_dataset(
        "result_position",
        data=np.asarray(output["result_position"], dtype=np.int16),
    )
    h5_file.create_dataset(
        "mixture_index",
        data=np.asarray(output["mixture_index"], dtype=np.int32),
    )
    h5_file.create_dataset(
        "source_number",
        data=np.asarray(output["source_number"], dtype=np.int16),
    )
    h5_file.create_dataset(
        "snr",
        data=np.asarray(output["snr"], dtype=np.float32),
    )
    h5_file.create_dataset(
        "reconstruction_quality",
        data=np.asarray(output["reconstruction_quality"], dtype=np.int8),
    )

    for name in (
        "source_reconstructed",
        "source_reconstructed_std",
        "source_real",
        "residual_reconstructed",
        "residual_reconstructed_std",
        "residual_real",
    ):
        h5_file.create_dataset(
            name,
            data=np.stack(output[name]),
            compression="gzip",
        )

    for parameter_name, values in parameter_values.items():
        h5_file.create_dataset(
            parameter_name,
            data=np.stack(values),
        )

print(f"Created: {OUTPUT_PATH}")
print(f"Sources are means over {sampling_counts[0]} aligned samplings.")
print("Contents:")
with h5py.File(OUTPUT_PATH, "r") as h5_file:
    for name, dataset in h5_file.items():
        print(f"  {name:30s} shape={dataset.shape}, dtype={dataset.dtype}")
